wpa_supplicant_extra: 
- |
  # Hackeriet home net <3
  network={
      ssid="hackeriet.no"
      psk="hackeriet.no"
  }
- |
  # 38C3 event network
  network={
     ssid="38C3"
     key_mgmt=WPA-EAP
     eap=TTLS
     identity="38C3"
     password="38C3"
     # ca path on debian 7.x and raspberry pi OS, modify accordingly
     ca_cert="/etc/ssl/certs/ISRG_Root_X1.pem"
     altsubject_match="DNS:radius.c3noc.net"
     phase2="auth=PAP"
  }
