---
- name: "Restart chrony"
  systemd:
    daemon_reload: true
    name: "chrony.service"
    state: "restarted"

- name: "Reload SSH"
  systemd:
    daemon_reload: true
    name: "sshd"
    state: "reloaded"

- name: "Update apt cache"
  apt:
    update_cache: true

- name: "Reload WPA supplicant"
  # https://raspberrypi.stackexchange.com/a/73847
  systemd:
    daemon_reload: true
    name: "dhcpcd"
    state: "restarted"
