---
##
## Pre-tasks
##
- name: Global pre tasks
  hosts: linux
  remote_user: root
  gather_facts: false
  pre_tasks:
  - name: Verify Ansible meets version requirements.
    assert:
      that: "ansible_version.full is version_compare('2.16', '>=')"
      msg: >
        "You must update Ansible to at least 2.16."

  - name: Install ansible dependencies (python)
    # install python3-apt to avoid needlesly triggering the next test
    raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3-minimal python3-apt)
    changed_when: false  # raw has no change handler

  - name: Install ansible dependencies (python3-apt)
    raw: test -e /usr/lib/python3/dist-packages/apt/package.py || (apt-get -y update && apt-get install -y python3-apt)
    changed_when: false  # raw has no change handler

###
### Common roles
###

# # Workaround for https://github.com/ansible/ansible/issues/57529
# - hosts: all

- name: Common roles
  hosts: linux
  remote_user: root
  tags: [common]
  roles:
  - common

- name: Raspberry Pis
  hosts: pi
  remote_user: root
  roles:
  - pi
